<template>
  <div>
    <iframe
      width="100%"
      height="480px"
      src="https://www.watchisup.fr/compte-a-rebours/embed/2024-12-24-19-00?backgroundcolor=&color="
      frameborder="0"
      allowfullscreen
    ></iframe>
  </div>
</template>
